### ISSUE TITLE
Using not just one Sync Flag but both for alligning the lines within the image grid

### ISSUE THREAD

**Issue by hornig** [aerospaceresearch/DirectDemod#10]
https://github.com/aerospaceresearch/DirectDemod/blob/fd2ee400931a0a298b128d2a16e6c2d7805d3c3b/directdemod/decode_noaa.py#L82-L124

currently, only Sync A is used for syncing the pixels of one line to the start of the image grid.
The Sync B in the middle of the image grid is not used so far.

In case of a sample frop during the first half of the line, the following half can be alligned as well. By this, distoration will only be effecive in the first half.

**Comment by 7andahalf** [comment]
Test example:
Before
![before image](https://user-images.githubusercontent.com/1297322/41193716-e46ce2ac-6c2d-11e8-9c2e-301462543783.png)
After
![after image](https://user-images.githubusercontent.com/1297322/41193717-e4a44eae-6c2d-11e8-8f23-d9afb4a48cff.png)

**Comment by hornig** [comment]
nice!
that is a great improvement and it will improvement the 2nd image a lot. in case of sample drops. :)
