### ISSUE TITLE
Use both Sync Flags (A and B) for distributing the pixels adeptively (doppler shift & sample drop)

### ISSUE THREAD

**Issue by hornig** [aerospaceresearch/DirectDemod#11]
https://github.com/aerospaceresearch/DirectDemod/blob/fd2ee400931a0a298b128d2a16e6c2d7805d3c3b/directdemod/decode_noaa.py#L82-L124

The Sync flags are reference markers within the signals. All following pixel informations are alligned and distrubted in between them.
Due to two reasons the the pixels "size" is not equally distrbuted with respect to time.
1) due to doppler shift
2) sample drops

by knowing the syn c flag positions, the doppler shift effect can be compensated by having difference bin sizes per pixel.
and also in case of drops of samples the effect can be mildered by this method.

So, an optional adaptive pixel size would be an enhancement.

pixel_size_per_step = pixel_count / (flagB_position - flagA_position)

Note:
This cna be done AFTER the previous issue with knowing the position of the syn flag with respect to the image grid. these are the known positions!

**Comment by 7andahalf** [comment]
Test image:
Before
![before](https://user-images.githubusercontent.com/1297322/41193829-f1d58b0e-6c2f-11e8-9eb6-90bd8c8995d4.png)
After
![after](https://user-images.githubusercontent.com/1297322/41193830-f210ac5c-6c2f-11e8-8a07-531fb15de0a4.png)

**Comment by hornig** [comment]
nice!
for just a few pixels offset, it should not be so problematic to distribute them differently :).
we still need to check how it behaves when there is a big sample drop. and also check how "big" is big.
nevertheless, this is an optical improvement.
thank you
