### ISSUE TITLE
Also open .dat files containing iq raw baseband data

### ISSUE THREAD

**Issue by hornig** [aerospaceresearch/DirectDemod#12]
https://github.com/aerospaceresearch/DirectDemod/blob/fd2ee400931a0a298b128d2a16e6c2d7805d3c3b/directdemod/source.py#L53

the .wav files we imported so far were recorded by SDR# programme.

the rtlsdr community uses also .dat files with the raw iq baseband output from the rtlsdr dongle.
DirectDemod shall be able to also import raw iq baseband. Then we also need to have either files with meta data of the recording, or the user need to provide the input data like center frequency, sample rate and so on that is stored in the .wav file.

**Comment by 7andahalf** [comment]
commits SHA-562b266004522996d62f06024c91b4022df2a230 SHA-fa9a86277a69c068d3564033e053c5168e7c57f5 solve the issue.
